/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import javax.swing.JOptionPane;


/**
 *
 * @author 1gdaw06
 */
public class vventas extends javax.swing.JFrame {

    /**
     * Creates new form vcompra
     */
    public vventas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tfproducto = new javax.swing.JTextField();
        tfunidades = new javax.swing.JTextField();
        tfimporte = new javax.swing.JTextField();
        vcomprabaceptar = new javax.swing.JButton();
        vcomprabcancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Ventana Ventas");

        jLabel2.setText("Producto");

        jLabel3.setText("Unidades");

        jLabel4.setText("Importe");

        tfproducto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfproductoFocusLost(evt);
            }
        });

        tfunidades.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfunidadesFocusLost(evt);
            }
        });

        tfimporte.setEditable(false);
        tfimporte.setBackground(new java.awt.Color(204, 204, 204));

        vcomprabaceptar.setText("Aceptar");
        vcomprabaceptar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                vcomprabaceptarMouseClicked(evt);
            }
        });

        vcomprabcancelar.setText("Cancelar");
        vcomprabcancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                vcomprabcancelarMouseClicked(evt);
            }
        });
        vcomprabcancelar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                vcomprabcancelarKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(105, 105, 105))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfproducto)
                            .addComponent(tfunidades)
                            .addComponent(tfimporte, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(vcomprabaceptar)
                        .addGap(68, 68, 68)
                        .addComponent(vcomprabcancelar)))
                .addContainerGap(96, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfproducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfunidades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfimporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vcomprabaceptar)
                    .addComponent(vcomprabcancelar))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void vcomprabaceptarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vcomprabaceptarMouseClicked
        if(ValidarProducto() && ValidarUnidades()){
            String producto = tfproducto.getText();
            int unidades = Integer.parseInt(tfunidades.getText());
            int importe = practica.ig4.PracticaIG4.AñadirVenta(producto, unidades); //se genera la venta
            tfimporte.setText(String.valueOf(importe));
        }
    }//GEN-LAST:event_vcomprabaceptarMouseClicked

    private void vcomprabcancelarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_vcomprabcancelarKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_vcomprabcancelarKeyPressed

    private void vcomprabcancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vcomprabcancelarMouseClicked
        this.dispose();
    }//GEN-LAST:event_vcomprabcancelarMouseClicked

    private void tfproductoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfproductoFocusLost

    }//GEN-LAST:event_tfproductoFocusLost

    private void tfunidadesFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfunidadesFocusLost
        
    }//GEN-LAST:event_tfunidadesFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vventas().setVisible(true);
            }
        });
    }
    
    public boolean ValidarProducto(){
        boolean ok = false;
        try{
            String producto = tfproducto.getText();
            for(String elemento : practica.ig4.PracticaIG4.productos){
                if(producto.equalsIgnoreCase(elemento)){
                    ok = true;
                }            
            }
            if(!ok){
                throw new Exception("Debes ingresar un producto de los ya definidos");
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, "ERROR -->" + e.getMessage());
        }
        return true;
        
    }
    
    public boolean ValidarUnidades(){
        try{
            if(!tfunidades.getText().isEmpty()){
                Integer.parseInt(tfunidades.getText());
            }
            else{
                throw new Exception("El campo \"Unidades\" no debe estar vacio");
            }
            
        }
        catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this, "Solo se pueden introducir digitos en el campo unidades");
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, "ERROR -->" + e.getMessage());
        }
        return true;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField tfimporte;
    private javax.swing.JTextField tfproducto;
    private javax.swing.JTextField tfunidades;
    private javax.swing.JButton vcomprabaceptar;
    private javax.swing.JButton vcomprabcancelar;
    // End of variables declaration//GEN-END:variables
}
