/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Excepciones.*;
import Modelo.Curso;
import javax.swing.JOptionPane;
import Modelo.Persona;
import java.awt.Color;
import javax.swing.JTextField;
import practica.ig.pkg3.PracticaIG3;
import static practica.ig.pkg3.PracticaIG3.*;

/**
 *
 * @author 1gdaw06
 */
public class VIN extends javax.swing.JFrame {

    /**
     * Creates new form VIN
     */
    public VIN() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tfnombre = new javax.swing.JTextField();
        tfapellidos = new javax.swing.JTextField();
        tfdni = new javax.swing.JTextField();
        baceptar = new javax.swing.JButton();
        bsalir = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        tfcurso = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("ALTA DE PERSONAS");

        jLabel2.setText("Nombre:");

        jLabel3.setText("Apellidos:");

        jLabel4.setText("DNI");

        baceptar.setText("Aceptar");
        baceptar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                baceptarMouseClicked(evt);
            }
        });
        baceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                baceptarActionPerformed(evt);
            }
        });

        bsalir.setText("Salir");
        bsalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bsalirMouseClicked(evt);
            }
        });
        bsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsalirActionPerformed(evt);
            }
        });

        jLabel5.setText("Curso:");

        tfcurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfcursoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfnombre)
                            .addComponent(tfapellidos)
                            .addComponent(tfdni, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                            .addComponent(tfcurso)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(baceptar)
                        .addGap(47, 47, 47)
                        .addComponent(bsalir)))
                .addContainerGap(86, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfdni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfapellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tfcurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(baceptar)
                    .addComponent(bsalir))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsalirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bsalirActionPerformed

    private void baceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_baceptarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_baceptarActionPerformed

    private void baceptarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_baceptarMouseClicked
        String nombre = tfnombre.getText();
        String apellidos = tfapellidos.getText();
        String dni = tfdni.getText();
        String curso0 = tfcurso.getText();
        Curso curso1 = new Curso();
        if(ValidarDni(dni) && ValidarCurso(curso0) && ValidarNombreApellido(nombre) && ValidarNombreApellido(apellidos)){
            if(!DniRepetido(dni)){
                curso1 = PracticaIG3.GenerarCurso(curso0);
                PracticaIG3.GenerarPersona(nombre, apellidos, dni, curso1);
                JOptionPane.showMessageDialog(null, "Se ha añadido la persona");
            }
            else{
                int opcion = JOptionPane.showOptionDialog(this, "Esta persona ya esta dada de alta...Que desea hacer?", "Opciones Persona", JOptionPane.YES_NO_CANCEL_OPTION,
                        JOptionPane.QUESTION_MESSAGE, null, new Object[] { "Borrar persona", "Editar Curso"}, "Editar Curso");
                if(opcion == 0){
                    BorrarPersonaDni(dni);
                }
                if(opcion==1){
                    tfdni.setEnabled(false);
                    tfnombre.setEnabled(false);
                    tfapellidos.setEnabled(false);
                    tfcurso.setText("");
                    tfcurso.setBackground(Color.red);
                    if(ValidarCurso(curso0)){
                        curso1 = PracticaIG3.GenerarCurso(curso0);
                        EditarCurso(dni, curso1);
                        JOptionPane.showMessageDialog(this, "El curso ha sido modificado");
                    }
                }
            }
        }
    }//GEN-LAST:event_baceptarMouseClicked

    private void bsalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bsalirMouseClicked
        PracticaIG3.VINSalir();
    }//GEN-LAST:event_bsalirMouseClicked

    private void tfcursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfcursoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfcursoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VIN().setVisible(true);
            }
        });
    }
    
    public static boolean ValidarNombreApellido(String nombre){
        try{
            if(nombre.isEmpty()){
                throw new NombreApellidoNoValido(" El campo es obligatorio y solo se pueden introducir letras");
            }
            else{
                return true;
            }
        }
        catch(NombreApellidoNoValido e){
            JOptionPane.showMessageDialog(null, "Error --> " + e.getMessage());
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error desconocido -->" + e.getMessage());
        }
        return false;
    }
    
    public static boolean ValidarDni(String dni){
        try{
            if(!dni.matches("[0-9]{8}[a-z A-Z]") || dni.isEmpty()){
                throw new FormatoDniNoValido("El campo es obligatorio y el formato es XXXXXXXXJ");
            }
            else{
                return true;
                }
            }
        catch(FormatoDniNoValido e){
            JOptionPane.showMessageDialog(null, "Error --> " + e.getMessage());
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error desconocido -->" + e.getMessage());
        }
        return false;
    }
    
    
    public static boolean ValidarCurso(String curso){
        try{           
            if(curso.matches("^[1-4] [abcdABCD]$")){
                return true;
            }
            else{
                throw new CursoNoValido("Ingresa el curso con el formato: 4 B");
            }
        }
        catch(CursoNoValido e){
            JOptionPane.showMessageDialog(null, e.getMessage());
            return false;
        }
    }
    
    public void ResaltarCurso(){
        tfcurso.requestFocus();
        tfcurso.setForeground(Color.red);
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton baceptar;
    private javax.swing.JButton bsalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField tfapellidos;
    private javax.swing.JTextField tfcurso;
    private javax.swing.JTextField tfdni;
    private javax.swing.JTextField tfnombre;
    // End of variables declaration//GEN-END:variables
}
